apiVersion: v1
kind: Pod
metadata:
  name: mlip
  labels:
    app: mlip
spec:
  containers:
  - name: mlip
    image: volodymyrsen/hello-world:latest
    command: ["/bin/bash"]
    stdin: true
    tty: true
