name: Python Code Quality

on: [push]

jobs:
  verify_dependencies:
    name: Verify Dependencies Lock File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv lock --locked

  code_linting:
    name: Run Code Linting Checks
    runs-on: ubuntu-latest
    needs: [verify_dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .

  code_formatting:
    name: Verify Code Formatting
    runs-on: ubuntu-latest
    needs: [verify_dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .

  type_checking:
    name: Run Type Checking
    runs-on: ubuntu-latest
    needs: [verify_dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pyright .

  unit_tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest
    needs: [verify_dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pytest -v --durations=0 --cov --cov-report=xml

  package_build:
    name: Build Python Package
    runs-on: ubuntu-latest
    needs: [code_linting, code_formatting, type_checking, unit_tests]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build
