name: Deploy Image to AWS ECR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  package_build:
    name: Build Python Wheel
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build
