name: Deploy Image to AWS ECR

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  verify_dependencies:
    name: Build and Push Docker Image to the ECR
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/assume-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
